// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDczgRVryUYkLo_n6Y1-ju8dNit7wB0WvM',
    appId: '1:884854012857:web:edfceb1fe346a668a0d468',
    messagingSenderId: '884854012857',
    projectId: 'flutter-starter-template-71810',
    authDomain: 'flutter-starter-template-71810.firebaseapp.com',
    storageBucket: 'flutter-starter-template-71810.appspot.com',
    measurementId: 'G-PMGP6JE16R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggzTvDIjkh-sXEvESagluhAfwp26HqKo',
    appId: '1:884854012857:android:d2804331507525b4a0d468',
    messagingSenderId: '884854012857',
    projectId: 'flutter-starter-template-71810',
    storageBucket: 'flutter-starter-template-71810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHzmCfSTtzt8EEZJREVDowrFaQSqdN9rA',
    appId: '1:884854012857:ios:c30a594acb1cdeaba0d468',
    messagingSenderId: '884854012857',
    projectId: 'flutter-starter-template-71810',
    storageBucket: 'flutter-starter-template-71810.appspot.com',
    iosBundleId: 'com.example.flutterStarterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHzmCfSTtzt8EEZJREVDowrFaQSqdN9rA',
    appId: '1:884854012857:ios:6f5fe54da628264ca0d468',
    messagingSenderId: '884854012857',
    projectId: 'flutter-starter-template-71810',
    storageBucket: 'flutter-starter-template-71810.appspot.com',
    iosBundleId: 'com.example.flutterStarterTemplate.RunnerTests',
  );
}
